### ISSUE TITLE
Optimizing Image Compression with Clop: A Workflow Enhancement

### ISSUE THREAD

**Issue by Awyugan** [FuzzyIdeas/Clop#18]
When using Clop for image compression, specifically for converting JPEG or PNG files, a notable issue arises. The tool employs two distinct processing logics depending on the file detail, which complicates the process of directly overwriting the original images. This approach introduces an additional step and associated costs for file replacement.

I want to directly overwrite the original file to reduce the number of steps.

**Comment by alin23** [comment]
This looks GPT generated and I'm sorry if it isn't but I don't understand your problem. Can you please use your own words and write what actions you're doing with Clop, what happens and what you expect should happen instead?

**Comment by Awyugan** [comment]
I took a screenshot of a picture. This picture is relatively large. I want to use clop to compress it.
But there was a problem during batch compression: some PNG pictures were compressed into smaller jpegs. At this time, two pictures 1.name.png 2 name.jpeg appeared in the folder, but the contents of the two pictures were the same.
Now I just need the optimized image to cover the unoptimized file.

**Comment by alin23** [comment]
PNGs were converted to JPEGs because they contained details that compress better with the JPEG algorithm. If you want to disable this behavior, then uncheck **Adaptive Optimisation**:

![Clop-005513-Friday-22-24](https://github.com/FuzzyIdeas/Clop/assets/3819725/0cfae5f8-5dda-4ba8-9780-76bd9fceff53)

If you want to keep the JPEG and have it replace the PNG, set the **Converted image location** setting to **In-place**.
