### ISSUE TITLE
Respect Strip EXIF Metadata for video optimisation

### ISSUE THREAD

**Issue by Splurov** [FuzzyIdeas/Clop#20]
When Strip EXIF Metadata is disabled video optimisation still remove meta such as coordinates.

How to reproduce:
- Get a video with Latitude and Longtitude (like from iPhone with default Camera settings), can check with CMD+I
- In Clop settings disable option Strip EXIF Metadata
- In Finder right click on a video and choose Optimise with Clop
- After optimisation metadata is missing

It would be nice to respect this setting also for video optimisation.

**Comment by alin23** [comment]
I see the EXIF metadata still there after optimising through Finder. Here's a demo video where I print the coordinates before and after optimising a video:

https://github.com/FuzzyIdeas/Clop/assets/3819725/95a3c5a6-abf1-4089-97b5-b6adfc8ac6d0

In the video I'm also highlighting the command in the Clop logs that does the transfer of EXIF metadata between the original and the optimised file.

I have also tried the same with a video that is saved through the **Export unmodified original** action of Photos.app and it works the same.

Maybe you can send some logs and also check that the metadata is there with `exiftool` instead of Finder.

Logs can be streamed with the following command:

```sh
log stream --level debug --style compact --process Clop --predicate 'subsystem BEGINSWITH "com.lowtechguys.Clop"' | tee ~/Desktop/clop.txt
```

**Comment by Splurov** [comment]
You are right. Works as expected when looking with exiftool. Looks like Finder uses some other data which is stripped. Sorry for wrong report. Closing.
