### ISSUE TITLE
[FEATURE] Support for .zip files

### ISSUE THREAD

**Issue by Romachamp** [FuzzyIdeas/Clop#31]
Hello, I would like Clop to support unarchiving and compressing .zip files as well as .rar files(optional). This would add to Clop more features and let me uninstall Keka/Unarchiver, because it has many more features. 

Please, consider implementing this. 

Thank you, in advance!

**Comment by alin23** [comment]
Thank you for the feature request! Although, Clop's core feature set does not have anything in common with unarchivers, so this does not fit in Clop.

There's no reason why a single app should have all the features, that makes the app worse not better, because a single developer cannot master all the knowledge needed to maintain all these features. It's better to have separate apps for these **very** different features _(compressing video/image data and archiving/unarchiving arbitrary files are not very similar in implementation)._
