### ISSUE TITLE
Quicklook ⌘Space shortcut clashes with Spotlight. Cannot seem to change shortcuts in settings, only turn off/on

### ISSUE THREAD

**Issue by mimkorn** [FuzzyIdeas/Clop#40]
Quicklook ⌘Space shortcut clashes with Spotlight. Cannot seem to change shortcuts in settings, only turn off/on

Cleanshot X (similar app) uses Space when hovering over the item. I would like the same -> show quicklook with space only when hovering over

**Comment by alin23** [comment]
The Command Space key is only being used on hover, it's not global. Maybe make sure you haven't changed the modifiers in Clop Settings -> Hotkeys tab to Command. 


You can also press Shift while hovering to quick look like Cleanshot does.

**Comment by mimkorn** [comment]
Hi, it doesn't work even when on hover. Observe in the gif (the clop isn't visible in the gif, but it's there, as you can see the dropdown when I click in that space with right click)

![CleanShot 2024-11-02 at 15 45 57](https://github.com/user-attachments/assets/17e5abcc-a256-495d-8437-45705fa6b7b2)

Through trials I just found out that even though the dropdown says ⌘Space and my settings look like the following:

![CleanShot 2024-11-02 at 15 50 30](https://github.com/user-attachments/assets/aebb55d0-b26b-4779-8c80-5f25d93ba6ec)

I can see the preview when on hover pressing ⇧Space and ⇧^Space. It's a little bit quirky, but I can now open up the preview like this and it's enough for me. But sending as FYI, cause it's probably a bit less than what would be expected behavior. 

Thanks for the app, it's great.

**Comment by alin23** [comment]
Looks like you're confusing the hotkeys a bit 😅 let me try to explain this better:

- The hotkeys inside the Clop settings window at the **Keyboard Shortcuts** tab are **global**, they work regardless if Clop is being hovered or not, in focus or not, and those have <kbd>Ctrl</kbd>-<kbd>Shift</kbd> as default modifiers which can be changed
- The hotkeys that you see in the right click menu are **local,** meaning they only work when you hover the result. <kbd>Command Space</kbd> doesn't work for you because Spotlight is getting more priority, that's why pressing <kbd>Shift</kbd> is also a possibility
- <kbd>Shift</kbd>-<kbd>Space</kbd> is not a valid hotkey, you only have to press <kbd>Shift</kbd> to toggle QuickLook on the hovered result. <kbd>Shift</kbd>-<kbd>Space</kbd> works simply because it contains <kbd>Shift</kbd>, the Space key does nothing to it.


I understood your problem differently at first, I thought you were saying that Clop blocks Spotlight with Command Space. So disregard my first comment as it doesn't make sense regarding your real issue. 

I'll close the issue as you can simply press Shift to trigger quicklook on hover. I can't show Shift in the right click menu, it's a limitation of macOS, that's why you only see Command Space there.
